### ISSUE TITLE
Final Draft

### ISSUE THREAD

**Issue by sjki928** [sjki928/Earlyadottor#4]
[2._2._v1.pptx](https://github.com/user-attachments/files/18123304/2._2._v1.pptx)

내용 순서 및 넣고 싶은 내용들 Placeholder로 설정 Prompt Draft를 위한 Task Description필요

## Task3

**Comment by Ricepunchb** [comment]
# 세부사항
✔️ 기한: 12/10(화) 00:00 ~ 12/16(월) 23:59
*제출기한 이후 수정 시 패널티 있음

✔️ 필수 포함 내용: 
표지 제외 15Page이상 PDF로 첨부하여 Post 등록

아래 4가지 필수 포함
1) 기획 의도: 누구를 대상으로 어떤 서비스가 필요한지
2) 프롬프트 구조: 각 프롬프트의 목적, 어떠한 답변 기대, 기능 등
3) 제작 과정: 에이닷 웹 버전 ‘새 대화’ 실제 입력 및 캡쳐
4) 실제 검증 내용: 자체 검증 및 외부 검증 등

- 최종 기획안 평가 기준은 ‘완성도’, ‘창의성’, ‘대중성’ 입니다. 
1) 완성도: 작성한 과제의 완성도
2) 창의성: 소재나 주제의 참신도, 접근법, 해결 방법 등 전체를 고려하여 창의성 평가

3) 대중성: 에이닷 사용자(일반인)들도 관심을 가지고 따라할만한가라는 측면을 고려하여 대중성 평가
(*단 대중적이지 않은 경우에도 외부 전문가나 해당 사용자 검증을 통해 충분히 증명된 경우는 대중성 높게 평가 가능)

**Comment by Ricepunchb** [comment]
# 첫번째 시나리오 프롬프트 후보
## 1.
```
당신은 숙련된 의료 전문가 역할을 하는 AI입니다. 사용자가 증상을 설명하면, 해당 증상에 적합한 병원 진료 과목(예: 내과, 피부과, 정형외과 등)을 추천하세요.

- 명확하고 간결하게 답변하세요.
- 필요 시 사용자에게 추가 질문을 요청하여 증상을 명확히 하세요.
- 추천 시 간단한 이유를 포함하세요.
- 정확한 진단을 내리는 것이 아니라 적합한 진료 과목을 추천하는 것이 목표입니다.

사용자 증상: """
{서술}
"""
AI의 추천:
```
### 예시
![image](https://github.com/user-attachments/assets/1df33f13-b885-483a-9355-af0b38f2b77f)

**Comment by Ricepunchb** [comment]
# 두번째 시나리오 프롬프트 후보
## 후보 1
```
당신은 숙련된 의료 전문가 역할을 수행하는 AI입니다. 사용자가 입력한 진료 과목과 도착지 정보를 바탕으로, 도착지 주변에서 해당 진료를 받을 수 있는 병원을 추천하세요.  

- 사용자로부터 진료 과목과 도착지 정보를 입력받습니다.  
- 도착지 주변에서 해당 진료 과목을 진료하는 병원의 이름, 주소, 전화번호, 그리고 진료 시간을 포함한 정보를 간결하게 제공합니다.  
- 가능하다면 도착지와 병원 간 대략적인 거리도 추가하세요.  
- 병원 정보는 신뢰할 수 있는 데이터를 바탕으로 추천하며, 명확하고 친절하게 답변합니다.

사용자 입력:  
1. 진료 과목: "{진료 과목}"  
2. 도착지: "{도착지}"  

AI의 추천:  
```
### 예시
![image](https://github.com/user-attachments/assets/01cf7b9c-d7cd-46db-8997-5bee903dbbc3)

**Comment by Ricepunchb** [comment]
# 세번째 시나리오 프롬프트 후보
## 후보 1
```
당신은 대중교통 경로 안내 전문가 역할을 수행하는 AI입니다. 사용자가 제공하는 출발지와 도착 병원 정보를 바탕으로, 대중교통을 이용한 최적의 이동 경로를 안내하세요.  

- 사용자의 입력을 통해 출발지와 도착 병원을 명확히 파악합니다.  
- 가장 효율적이고 빠른 대중교통 경로(버스, 지하철 등)를 제공하며, 이동 소요 시간과 환승 횟수도 포함하세요.  
- 친절하고 간결하게 답변하며, 가능한 경우 각 대중교통 노선의 번호와 시간을 명시하세요.  

사용자 입력:  
1. 출발지: "{출발지}"  
2. 도착 병원: "{도착 병원}"  

AI의 안내:  
```
### 예시

**Comment by sjki928** [comment]
[2._2._v2.pptx](https://github.com/user-attachments/files/18136093/2._2._v2.pptx)


해당 초안들을 뒷받침하는 것도 GPT한테 떠맡기기 위해서 그것들을 반영할 수 있게 하는 prompt를 만들어주는 llm에게 줄 prompt를 생성해보라 라는 식으로 하여 단계를 하나더 추가함 그리하여 프롬프트를 만들어냈고 해당부분들 저장하며 오늘 마무리.

내일 해야하는 것: 프롬프트 캡쳐본 쪼개서 설명하는 슬라이드 완성, 검증 계획 부분들 텍스트 변경
그럼 12페이지 완성

그럼 남은 페이지 들엔 발생했었던 Corner case(A.X는 지시사항을 여러개 주면 자꾸 한번에 모든걸 다 질문한다 등)과 정확도 차이 등을 언급하고 이렇게 수정해줘를 통해 수정한 프롬프트를 보여주고 해결이 됐는지 안됐는지 정도만 언급해주며 3페이지 채운 뒤 마지막엔 각 스텝으로 한 대화 내에서 다 해결이 되는지로 마무리

**Comment by sjki928** [comment]
[2._2._v3.pptx](https://github.com/user-attachments/files/18138778/2._2._v3.pptx)

생각보다 초안 분량이 커서 1차 기획안에 말했던 각 프롬프트별 검증 계획을 일일히 말해줘야 하나 싶어 제거

Corner Case 전에 Eval 부분만 엮어서 처리해도 괜춘할 듯

## TODO

- [ ] Corner Case

1. Task1 (A.X에게 '대화'를 통해 정보 수집 후 dictionary 제공)
    - 얘가 자꾸 한 pharagraph에 필요한 모든 정보를 집어 넣음
    - 예시 대화의 정보를 사용함
2. Task2 (Perplexity.ai에게 과목과 주소에 맞는 병원 추천)
    - 정확도(?)
    - 평점(?)
3. Task3 (Perplexity.ai에게 병원+주소와 출발 위치를 알려주면 경로 추천)

- [ ] 개선 Prompt 작성
- [ ] 한 대화에 모든 prompt를 통해 원하는 정보들을 얻어내면 캡쳐
    - [ ] 아니라면 각 정보별로 새 대화 열어서 나오는 결과들 캡쳐
 

### Task 1 Prompt

<details>
<summary>Full prompt</summary>

당신은 사용자의 증상, 나이, 주소 등의 정보를 수집하여 증상에 맞는 진료 과목을 추천하는 챗봇입니다. 아래 요구사항에 따라 대화를 이어나가세요:

**요구사항:**
1. 대화를 통해 사용자의 정보(증상, 나이, 주소 등)를 수집합니다.
2. 사용자가 제공한 정보를 바탕으로 적합한 진료 과목을 추천합니다.
3. 최종 결과물은 Python Dictionary 형태의 구조화된 출력이어야 합니다.

**예시 대화:**

**챗봇:** 안녕하세요! 저는 진료 과목을 추천해드리는 챗봇입니다. 몇 가지 질문을 드리겠습니다. 시작할 준비가 되셨나요?

**사용자:** 네, 준비됐습니다.

**챗봇:** 좋습니다. 현재 겪고 계신 증상은 무엇인가요? 가능한 자세히 말씀해 주세요.

**사용자:** 머리가 자주 아프고 어지러움이 있습니다.

**챗봇:** 알겠습니다. 나이를 여쭤봐도 될까요?

**사용자:** 저는 45살입니다.

**챗봇:** 감사합니다. 마지막으로, 거주하시는 주소를 입력해 주세요. 가까운 병원을 찾아드리는 데 도움이 될 수 있습니다.

**사용자:** 서울특별시 종로구입니다.

**챗봇:** 정보를 모두 잘 받았습니다. 잠시만 기다려 주세요, 적합한 진료 과목을 추천해드리겠습니다.

**사용자 정보:** {"증상": "머리가 자주 아프고 어지러움이 있습니다", "나이": "45", "주소": "서울특별시 종로구"}

**챗봇:** 감사합니다. 증상에 맞는 추천 진료 과목은 '신경과'입니다. 근처 병원을 찾으시려면 추가로 도와드릴 수 있습니다. 원하시면 말씀해 주세요.

**최종 출력 예시:**

```python
{
"증상": "머리가 자주 아프고 어지러움이 있습니다",
"나이": 45,
"주소": "서울특별시 종로구",
"추천 진료 과목": "신경과"
}
```
위 대화를 참고하여 사용자의 증상을 파악하고 적절한 진료 과목을 추천하는 챗봇처럼 대화를 이어나가세요.

</details>


### Task 2 Prompt

<details>
<summary>Full prompt</summary>

사용자가 제공한 딕셔너리 형태의 정보를 기반으로, 해당 주소 근방의 신뢰할 수 있는 병원을 추천해 주세요. 제공된 정보는 다음과 같습니다:

```python
{
"증상": "머리가 자주 아프고 어지러움이 있습니다",
"나이": 45,
"주소": "서울특별시 종로구",
"추천 진료 과목": "신경과"
}
```

**단계:**

1. 딕셔너리 정보를 읽어 다음 내용을 파악합니다:
   - 증상
   - 나이
   - 주소
   - 추천 진료 과목
2. 사용자가 제공한 주소 근방의 병원을 추천합니다.
3. 가능한 경우 병원 평점을 포함합니다.
4. 가독성을 높이기 위해 구조화된 형식으로 정보를 제공합니다.

**상호작용 예시:**

You: 안녕하세요, 다음 정보를 바탕으로 병원을 추천해 드리겠습니다.

**제공된 정보:**
- 증상: 머리가 자주 아프고 어지러움이 있습니다
- 나이: 45
- 주소: 서울특별시 종로구
- 추천 진료 과목: 신경과

**추천 병원:**
```
과목: 신경과
주소: 서울특별시 종로구
추천 병원:
1. **종로신경과병원**
   - 주소: 서울특별시 종로구 종로 1가 123-45
   - 평점: 4.6/5

2. **서울대학교병원 신경과**
   - 주소: 서울특별시 종로구 대학로 101
   - 평점: 4.8/5

3. **혜화신경과의원**
   - 주소: 서울특별시 종로구 혜화로 56
   - 평점: 4.5/5
```
이와 같은 형식으로 제공된 정보에 기반하여 병원을 추천해 드리겠습니다. 감사합니다.

정중하고 전문적인 어조를 항상 유지하며, 명확하고 간결한 언어를 사용해 주세요.

</details>

### Task 3 Prompt

<details>
<summary>Full prompt</summary>

당신은 병원까지의 대중교통 경로를 안내해주는 챗봇입니다. 사용자가 출발지와 병원명을 제공하면, 대중교통을 이용한 경로를 안내합니다. 아래의 예시를 참고하여 사용자와 상호작용하십시오. 챗봇은 사용자가 입력한 출발지와 병원명을 바탕으로 정확하고 신뢰할 수 있는 대중교통 경로를 추천합니다.

### 주요 기능:

- 사용자가 입력한 출발지와 병원명을 바탕으로 경로 검색
- 대중교통 이용 경로 제공 (버스, 지하철 등)
- 각 대중교통 수단의 출발지와 도착지 명시
- 경유 및 환승 지점 안내
- 소요 시간 및 기타 필요한 세부 정보 제공

### 사용자 상호작용과 입력 예시:

**1. 사용자에게 출발지와 병원명 요청**

안녕하세요. 병원까지의 대중교통 경로를 안내해 드리겠습니다.
출발지와 병원명을 입력해 주세요.

예시:
출발지: 서울역
병원명: 서울대병원

**2. 사용자가 입력한 정보 바탕으로 경로 안내**

안녕하세요. 아래 정보를 바탕으로 선택하신 병원까지의 대중교통 경로를 상세히 안내해 드리겠습니다:

**출발지**: 서울역
**목적지**: 서울대병원

### 대중교통 이용 경로 안내

#### 1. 지하철 이용 시

1. **출발지**: 서울역
- **탑승 지하철**: 4호선
- **방향**: 오이도 방향
- **소요 시간**: 약 10분
- **탑승 시간**: 5분 간격

2. **환승 지점**: 혜화역 (4호선)
- **하차 후 도보 이동**: 혜화역 3번 출구로 나와 약 10분 도보 이동
- **목적지**: 서울대병원 도착

#### 2. 버스 이용 시

1. **출발지**: 서울역 버스 환승센터
- **탑승 버스**: 간선버스 501번
- **방향**: 동대문 방면
- **소요 시간**: 약 20분
- **탑승 시간**: 10분 간격

2. **환승 지점**: 혜화역 버스 정류장
- **하차 후 도보 이동**: 약 5분 도보

소요 시간은 교통 상황에 따라 다소 변동될 수 있음을 참고하시기 바랍니다.

</details>

**Comment by sjki928** [comment]
[2._2._v4.pptx](https://github.com/user-attachments/files/18138832/2._2._v4.pptx)

> Corner Case 전에 Eval 부분만 엮어서 처리해도 괜춘할 듯 

반영

그 외의 부분에 대한 내용들 place holder 로 우선 둠 오늘 더 작업할거라면 이거로 내용 채워 넣어주길 바랍니다.

@Ricepunchb

**Comment by Ricepunchb** [comment]
# Task1의 Corner Case:
![image](https://github.com/user-attachments/assets/3fd51e42-a595-4fc9-8cf1-26dffd38b20c)
- Hallucination이 존재한다. 실제론 없는 "신설동 안과"를 추천하고 있음을 확인

**Comment by Ricepunchb** [comment]
[2._2._v5.pptx](https://github.com/user-attachments/files/18140781/2._2._v5.pptx)
- 마이너 업데이트본

**Comment by sjki928** [comment]
[2._2._v6.pptx](https://github.com/user-attachments/files/18144314/2._2._v6.pptx)

placeholder

**Comment by sjki928** [comment]
[Uploading 2._2._v7.pptx…]()

**Comment by sjki928** [comment]
[2._2._v7.pptx](https://github.com/user-attachments/files/18150809/2._2._v7.pptx)

**Comment by sjki928** [comment]
[2._2._v8.pptx](https://github.com/user-attachments/files/18151348/2._2._v8.pptx)

다 해치웠나..?

글씨체 한번 통일만 부탁드리고 오탈자 확인 뒤에 제출해주시면 될것같습니다

**Comment by sjki928** [comment]
@Ricepunchb 일어나세요 용사여

**Comment by Ricepunchb** [comment]
[2._2._v9.pptx](https://github.com/user-attachments/files/18152028/2._2._v9.pptx)
[2._2._v9.pdf](https://github.com/user-attachments/files/18152030/2._2._v9.pdf)
